In [1]:
# Import the needed libraries
import numpy as np

**72. How to swap two rows of an array?** 

In [5]:
array = np.array([[3,9,7],[4,6,8]])
array[[0,1]] = array[[1,0]]

print(array)

[[4 6 8]
 [3 9 7]]


**75. How to compute averages using a sliding window over an array?**

In [13]:
def moving_average(a, window_size = 5):
    sums = np.cumsum(a)
    sums[window_size:] = sums[window_size:] - sums[:-window_size]
    return sums[window_size-1:]/window_size

array = np.array([1,2,3,4,5,6,7,8,9,10])
moving_average(array)

array([3., 4., 5., 6., 7., 8.])